[BAAS-189] add route tag and wallet type enum
arxanchain/java-common pull request #5
Opened 2018-08-10 08:36 UTC by ivy-dong

2018-08-11 15:55 UTC, ewangplay requested changes

2018-08-11 15:55 UTC, ewangplay commented on src/main/java/com/arxanfintech/common/rest/Client.java
> +    public String RouteTag;
这个RouteTag是需要在发送请求时设置到Http header中的（key就是RouteTag)，这个操作应该在java-common中统一处理，而不应该在各个具体的SDK中去处理。请仔细参考sdk-go-common/rest/api中是怎么对RouteTag进行处理的。

2018-08-13 11:18 UTC, ivy-dong commented on src/main/java/com/arxanfintech/common/rest/Client.java
> +    public String RouteTag;
done

2018-08-21 03:04 UTC, ewangplay approved these changes

2018-08-21 03:05 UTC, merged